name: Publish Nuget
on: push
jobs:
    Publish:
        runs-on : ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v1
            - name: Build
              run: dotnet build -c Release
            - name: Test
              run: dotnet test -c Release --no-build
            - name: Pack nuget
              run : dotnet pack -c Release 
            - name: Push to nuget
              run: dotnet nuget push "bin/Release"  --api-key ${{secrets.nuget_api_key}} --source "https://github.com/prithvijith"
            #run: dotnet nuget push "bin/Release/PROJECT_NAME.1.0.0.nupkg" --source "github"
              # run:  dotnet nuget push ./path/to/your.nupkg --source "nuget.org" --api-key ${{ secrets.nuget_api_key }}
  #            run:  dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
              